sheet: 
  api_key: ""
  men:
    id: "1"
  women:
    id: ""
  cell_type_color:
    home:
      blue: 0.20784314
      green: 0.2627451
      red: 0.91764706
    away:
      blue: 0.7411765
      green: 0.7411765
      red: 0.7411765
    cup:
      blue: 0.95686275
      green: 0.52156866
      red: 0.25882354

slack:
  api_key: ""
  users:
    coachs:
      men:
        - name: ""
          id: ""
      women:
        - name: ""
          id: ""
      test:
        - name: ""
          id: ""
  message:
    common:
      header:
        type: ""
        text: ""
      info:
        type: ""
        text: ""
      end:
        type: ""
        text: ""
      help:
        type: ""
        text: ""
    men:
      list:
        type: ""
        text: ""
    women:
      list:
        type: ""
        text: ""